# Generated by Django 4.0.3 on 2022-03-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebcamML', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcampic',
            name='screenshot',
        ),
    ]
